### ISSUE TITLE
kitchen broken in azure

### ISSUE THREAD

**Issue by jmery** [chef-cft/bjc#545]
When accessing a fresh demo within Azure, kitchen is not configured properly.

1.  `.kitchen.local.yml` is empty
2.  `.kitchen.yml` has an ec2 driver pointed back at the AWS demo environment (which doesn't exist)

All kitchen commands fail because of this.

**Comment by jmery** [comment]
Working `.kitchen.yml`:

```
---
driver:
  name: azurerm

driver_config:
  subscription_id: 'b02e675a-cee0-49bd-a056-daa7ed05bf4e'
  location: 'West US'
  machine_size: 'Standard_D2_v2'

transport:
  ssh_key: ~/.ssh/id_rsa

provisioner:
  name: chef_zero
  require_chef_omnibus: 12

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
    driver_config:
      image_urn: Canonical:UbuntuServer:14.04.4-LTS:latest
      vm_name: trusty-vm
      vm_tags:
        ostype: linux
        distro: ubuntu
    transport:
      ssh_key: ~/.ssh/id_rsa

suites:
  - name: default
    run_list:
      - recipe[bjc-ecommerce::tksetup]
      - recipe[bjc-ecommerce::default]
    attributes:
    verifier:
      inspec_tests:
        - name: ssl-baseline
          url: https://github.com/dev-sec/ssl-baseline/archive/v1.1.1.tar.gz
```
